---
  - name: Adding admin group to sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      line: '%{{ generic_admins__groupname}}  ALL=(ALL)       NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
